# Generated by Django 6.1.1 on 2026-09-18 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingGround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='College Bus Parking Ground', max_length=100)),
                ('length_m', models.DecimalField(decimal_places=2, default=60.0, max_digits=6)),
                ('width_m', models.DecimalField(decimal_places=2, default=35.0, max_digits=6)),
                ('entrance_width_m', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('exit_width_m', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('total_slots', models.PositiveIntegerField(default=32)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=10)),
                ('slot_number', models.PositiveIntegerField()),
                ('x_position_m', models.DecimalField(decimal_places=2, max_digits=7)),
                ('y_position_m', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('bus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_slot', to='buses.bus')),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.parkingground')),
            ],
        ),
    ]
