# Generated by Django 4.2.30 on 2026-09-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_remove_ground_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='slot_type',
            field=models.CharField(choices=[('BUS', 'Bus'), ('RESERVED', 'Reserved'), ('CAR_BIKE', 'Car / Bike')], default='BUS', max_length=10),
        ),
        migrations.AlterField(
            model_name='parkingground',
            name='total_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='parkingslot',
            constraint=models.UniqueConstraint(fields=('ground', 'row', 'slot_number'), name='unique_ground_row_slot'),
        ),
    ]
