# Generated by Django 4.2.30 on 2026-09-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_backfill_reserved_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='is_unconfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
