# Generated by Django 4.2.30 on 2026-09-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_before', models.IntegerField(default=0)),
                ('blocked_after', models.IntegerField(default=0)),
                ('movements_required', models.IntegerField(default=0)),
                ('layout_json', models.TextField(default='{}')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
