# Generated by Django 4.2.30 on 2026-09-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationresult',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
