# Generated by Django 4.2.30 on 2026-09-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        ('parking', '0002_remove_ground_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=50)),
                ('session', models.CharField(default='default', max_length=40)),
                ('track_id', models.PositiveIntegerField()),
                ('candidate_count', models.PositiveSmallIntegerField(default=0)),
                ('x_m', models.FloatField(default=0)),
                ('y_m', models.FloatField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('frames_seen', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField()),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vision_tracks', to='buses.bus')),
                ('candidate_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='parking.parkingslot')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vision_tracks', to='parking.parkingslot')),
            ],
            options={
                'ordering': ['-last_seen'],
                'unique_together': {('camera_id', 'session', 'track_id')},
            },
        ),
    ]
