# Generated by Django 4.2.30 on 2026-09-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiontrack',
            name='bus_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
