# Generated by Django 4.2.30 on 2026-09-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_faceprofile'),
        ('students', '0002_student_linked_user'),
    ]

    operations = [
    ]
