# Generated by Django 4.2.30 on 2026-09-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_merge_0002_faceprofile_0002_student_linked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceprofile',
            name='retake_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
