# Generated by Django 4.2.30 on 2026-09-25 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0005_encrypt_face_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceProfileAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ENROLL', 'Enrolled'), ('REENROLL', 'Re-enrolled'), ('DELETE', 'Deleted'), ('ADMIN_READ', 'Admin viewed')], max_length=12)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_audit_entries', to='students.student')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
