# Generated by Django 6.1.1 on 2026-09-21 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('COMPLAINT', 'Complaint'), ('FEEDBACK', 'Feedback'), ('SUGGESTION', 'Suggestion')], default='COMPLAINT', max_length=12)),
                ('category', models.CharField(choices=[('BUS', 'Bus condition'), ('DRIVER', 'Driver'), ('ROUTE', 'Route or timing'), ('PARKING', 'Parking'), ('APP', 'This app'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField(max_length=2000)),
                ('author_role', models.CharField(blank=True, max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In review'), ('RESOLVED', 'Resolved')], default='NEW', max_length=10)),
                ('admin_note', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_sent', to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='buses.bus')),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
