# Generated by Django 4.2.30 on 2026-09-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_parkingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('RFID', 'RFID'), ('ULTRASONIC', 'Ultrasonic'), ('CAMERA', 'Camera')], max_length=20),
        ),
    ]
