# Generated by Django 4.2.30 on 2026-09-25 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkingslot_is_unconfirmed'),
        ('sensors', '0003_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('CAMERA_OFFLINE', 'Camera offline'), ('SLOT_UNCONFIRMED', 'Slot unconfirmed')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('parking_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='parking.parkingslot')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
