# Generated by Django 4.2.30 on 2026-09-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Transport Staff'), ('DRIVER', 'Driver'), ('STUDENT', 'Student'), ('INCHARGE', 'Cab In-Charge')], default='STUDENT', max_length=20),
        ),
    ]
