# Generated by Django 4.2.30 on 2026-09-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], help_text='Underlying Student/Teacher identity, separate from role.', max_length=10, null=True),
        ),
    ]
