# Generated by Django 4.2.30 on 2026-09-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact number shown to riders.', max_length=20),
        ),
    ]
