# Generated by Django 4.2.30 on 2026-09-24 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_bus_incharge'),
        ('attendance', '0007_teacher_linked_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TEACHER', 'Teacher roster link'), ('DRIVER_BUS', 'Driver bus claim')], max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=200)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_requests', to='buses.bus')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_decisions', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_requests', to='attendance.teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='linkrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user', 'kind'), name='one_pending_link_request_per_user_kind'),
        ),
        migrations.AddConstraint(
            model_name='linkrequest',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bus__isnull', True), ('kind', 'TEACHER'), ('teacher__isnull', False)), models.Q(('bus__isnull', False), ('kind', 'DRIVER_BUS'), ('teacher__isnull', True)), _connector='OR'), name='link_request_target_matches_kind'),
        ),
    ]
