# Generated by Django 4.2.30 on 2026-09-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_linkrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('key_hash', models.CharField(editable=False, max_length=200)),
                ('name', models.CharField(help_text="e.g. 'RFID reader - Gate 1'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
