# Generated by Django 4.2.30 on 2026-09-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_teacher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Transport Staff'), ('DRIVER', 'Driver'), ('STUDENT', 'Student'), ('INCHARGE', 'Cab In-Charge')], default='STUDENT', max_length=20),
        ),
    ]
