# Generated by Django 6.1.1 on 2026-09-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('rfid_uid', models.CharField(max_length=100, unique=True)),
                ('route', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
