# Generated by Django 4.2.30 on 2026-09-23 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buses', '0002_bus_driver_bus_student_capacity_bus_teacher_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='incharge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incharge_bus', to=settings.AUTH_USER_MODEL),
        ),
    ]
