# Generated by Django 4.2.30 on 2026-09-24 01:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_alter_attendancesession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceWindowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_start', models.TimeField(default=datetime.time(5, 0))),
                ('morning_end', models.TimeField(default=datetime.time(9, 30))),
                ('evening_start', models.TimeField(default=datetime.time(16, 30))),
                ('evening_end', models.TimeField(default=datetime.time(19, 30))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_window_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance window configuration',
                'verbose_name_plural': 'Attendance window configuration',
            },
        ),
    ]
