# Generated by Django 4.2.30 on 2026-09-24 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0004_attendancewindowconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('SCAN', 'QR/Face scan'), ('MANUAL', 'Manual mark by in-charge'), ('CORRECT', 'Corrected by staff/admin'), ('AUTO_ABSENT', 'Auto-marked absent')], max_length=15)),
                ('old_status', models.CharField(blank=True, max_length=10)),
                ('new_status', models.CharField(max_length=10)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(blank=True, max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='attendance.attendancerecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
