# Generated by Django 4.2.30 on 2026-09-24 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0006_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='linked_user',
            field=models.OneToOneField(blank=True, help_text='The login account of this teacher. Set only after staff approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
