# Generated by Django 4.2.30 on 2026-09-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_teacher_linked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceaudit',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('SCAN', 'QR/Face scan'), ('MANUAL', 'Manual mark by in-charge'), ('CORRECT', 'Corrected by staff/admin'), ('AUTO_ABSENT', 'Auto-marked absent'), ('SUBMIT', 'Driver submit'), ('REVOKE', 'Revoked by admin'), ('DELETE_BLOCKED', 'Delete attempt blocked')], max_length=15),
        ),
    ]
