# Generated by Django 4.2.30 on 2026-09-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_audit_more_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceaudit',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='row_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='attendance.attendancesession'),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
