# Generated by Django 4.2.30 on 2026-09-25 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0011_audit_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(choices=[('SAME_DEVICE_MANY_STUDENTS', 'One device used for many students'), ('SAME_IP_BURST', 'Many scans from one IP in a short window'), ('EMBEDDING_CLONE', 'Two students share a near-identical face embedding'), ('IDENTICAL_SCORES', 'Many scans share an unusually exact match score'), ('MANUAL_MARK_SHARE_HIGH', 'Unusually high share of manual marks in a session'), ('SESSION_INSTANT_PRESENT', 'Everyone marked present within one minute'), ('HOLIDAY_ATTENDANCE', 'Attendance recorded on a declared holiday')], max_length=32)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=6)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('records', models.ManyToManyField(blank=True, related_name='flags', to='attendance.attendancerecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_flags_reviewed', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
