# Generated by Django 4.2.30 on 2026-09-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendanceflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancewindowconfig',
            name='qr_token_ttl_seconds',
            field=models.PositiveIntegerField(default=10, help_text='How many seconds a generated attendance QR code stays valid before it expires.'),
        ),
    ]
