# Generated by Django 4.2.30 on 2026-09-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_attendancewindowconfig_qr_token_ttl_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceflag',
            name='rule',
            field=models.CharField(choices=[('SAME_DEVICE_MANY_STUDENTS', 'One device used for many students'), ('SAME_IP_BURST', 'Many scans from one IP in a short window'), ('EMBEDDING_CLONE', 'Two students share a near-identical face embedding'), ('IDENTICAL_SCORES', 'Many scans share an unusually exact match score'), ('MANUAL_MARK_SHARE_HIGH', 'Unusually high share of manual marks in a session'), ('SESSION_INSTANT_PRESENT', 'Everyone marked present within one minute'), ('HOLIDAY_ATTENDANCE', 'Attendance recorded on a declared holiday'), ('MANUAL_MARK_LOGGED', 'Manual mark by in-charge (informational)')], max_length=32),
        ),
    ]
