# Generated by Django 4.2.30 on 2026-09-26 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buses', '0003_bus_incharge'),
        ('attendance', '0014_alter_attendanceflag_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryInchargeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stand_ins', to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_incharge_assignments', to='buses.bus')),
                ('stand_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand_in_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='temporaryinchargeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('bus', 'date'), name='one_active_standin_per_bus_per_day'),
        ),
    ]
