# Generated by Django 4.2.30 on 2026-09-26 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_bus_incharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0015_temporaryinchargeassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INCHARGE_DELEGATED', 'Incharge role handed to a stand-in'), ('DELEGATION_ENDED', 'Delegation ended'), ('CABS_COMBINED', 'Cabs combined'), ('COMBINATION_ENDED', 'Cab combination ended'), ('MANUAL_MARK', 'Manual attendance mark or correction'), ('QR_SESSION_OPENED', 'QR session opened'), ('QR_SESSION_CLOSED', 'QR session closed'), ('FLAG_REVIEWED', 'Attendance flag reviewed')], max_length=32)),
                ('description', models.CharField(max_length=300)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_events_caused', to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_events', to='buses.bus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
