# Generated by Django 4.2.30 on 2026-09-26 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_bus_incharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0016_historyevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceflag',
            name='rule',
            field=models.CharField(choices=[('SAME_DEVICE_MANY_STUDENTS', 'One device used for many students'), ('SAME_IP_BURST', 'Many scans from one IP in a short window'), ('EMBEDDING_CLONE', 'Two students share a near-identical face embedding'), ('IDENTICAL_SCORES', 'Many scans share an unusually exact match score'), ('MANUAL_MARK_SHARE_HIGH', 'Unusually high share of manual marks in a session'), ('SESSION_INSTANT_PRESENT', 'Everyone marked present within one minute'), ('HOLIDAY_ATTENDANCE', 'Attendance recorded on a declared holiday'), ('MANUAL_MARK_LOGGED', 'Manual mark by in-charge (informational)'), ('CROSS_BUS_SCAN', 'Cross-bus scan under an active cab combination')], max_length=32),
        ),
        migrations.CreateModel(
            name='CabCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buses', models.ManyToManyField(related_name='combinations', to='buses.bus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cab_combinations_created', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cab_combinations_ended', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
